### ISSUE TITLE
Nexus

### ISSUE THREAD

**Issue by brycechesternewman** [Berico-Technologies/RabbidManagement#4]
Hi,
I am trying to access your Nexus.
Is http://nexus.bericotechnologies.com/content/groups/public still valid?

**Comment by rclayton-the-terrible** [comment]
@brycechesternewman Sorry no.  I left Berico Technologies and they have since taken down their Nexus server.  Let me ask John if he will push it into our Fallwizard repo.

@jar349 I forked this repo over to the Fallwizard Github organization.  Can we get it pushed to Maven Central?

**Comment by jar349** [comment]
I can do that, but I'd have to change the namespace of the code to io.github.fallwizard ... which is a bit strange for a rabbitMQ management library, but I'm willing to do it.  I think I'd change the artifact to be io.github.fallwizard:rabbitmq-mgmt:3.8.0.   Any problems with that?

**Comment by jar349** [comment]
or would you prefer io.github.fallwizard.rabbitmq:mgmt:3.8.0?

**Comment by rclayton-the-terrible** [comment]
@jar349 I like io.github.fallwizard:rabbitmq-mgmt:3.8.0.  Thanks.

**Comment by jar349** [comment]
Alright.  I'll look into pushing it tomorrow or Friday.

**Comment by kharel** [comment]
Hi,
any update on this?

**Comment by jar349** [comment]
Hah, yes.  The update is that I totally forgot until you commented.  I'll make the needed changes later today, and I'm sorry for the delay.

**Comment by brycechesternewman** [comment]
Hi guys. 
Thank you for responding. I ended up writing what I needed, but I am sure others will benefit from getting this up on maven.

**Comment by kharel** [comment]
Indeed...i need it badly :).
I really appreciate the effort

thanks!

**Comment by jar349** [comment]
FYI - I'm doing this now.  Should be uploaded to maven central in a few hours.

**Comment by jar349** [comment]
I've made the changes and uploaded the project to the staging repository.  It should show up in maven central in an hour or less, I'd guess.

**Comment by jar349** [comment]
FYI - I can't close issues any longer.  And besides, the main repository is now https://github.com/Fallwizard/RabbidManagement
